// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6buWim2adGUoyXn4F0vcYUl0W7dfnOY',
    appId: '1:1015716104447:web:b23140f444ce41f221e4ca',
    messagingSenderId: '1015716104447',
    projectId: 'otp-and-notification',
    authDomain: 'otp-and-notification.firebaseapp.com',
    storageBucket: 'otp-and-notification.firebasestorage.app',
    measurementId: 'G-8MJLDLD4LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7gwTFrzOBtUEhdyiAOzMIQZqvGpWDxQI',
    appId: '1:1015716104447:android:145043ba0700fcc621e4ca',
    messagingSenderId: '1015716104447',
    projectId: 'otp-and-notification',
    storageBucket: 'otp-and-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwxoLAgB3ws2FxF9wl4otc1VetYK6w0bs',
    appId: '1:1015716104447:ios:78e59ed3e1a1066f21e4ca',
    messagingSenderId: '1015716104447',
    projectId: 'otp-and-notification',
    storageBucket: 'otp-and-notification.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwxoLAgB3ws2FxF9wl4otc1VetYK6w0bs',
    appId: '1:1015716104447:ios:78e59ed3e1a1066f21e4ca',
    messagingSenderId: '1015716104447',
    projectId: 'otp-and-notification',
    storageBucket: 'otp-and-notification.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk6buWim2adGUoyXn4F0vcYUl0W7dfnOY',
    appId: '1:1015716104447:web:0071d53c1a0744c421e4ca',
    messagingSenderId: '1015716104447',
    projectId: 'otp-and-notification',
    authDomain: 'otp-and-notification.firebaseapp.com',
    storageBucket: 'otp-and-notification.firebasestorage.app',
    measurementId: 'G-GC5BMVZJST',
  );
}
